server.port=${PORT:8080}
server.require-ssl=true
server.use-forward-headers=true

salesforce.client-id=${SALESFORCE_CLIENT_ID}
salesforce.client-secret=${SALESFORCE_CLIENT_SECRET}
salesforce.redirect-uri=${SALESFORCE_REDIRECT_URI} 

spring.security.oauth2.client.registration.salesforce.client-id=${SALESFORCE_CLIENT_ID}
spring.security.oauth2.client.registration.salesforce.client-secret=${SALESFORCE_CLIENT_SECRET}
spring.security.oauth2.client.registration.salesforce.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.salesforce.redirect-uri={baseUrl}/login/oauth2/code/salesforce
spring.security.oauth2.client.registration.salesforce.scope=full,refresh_token
spring.security.oauth2.client.registration.salesforce.client-name=Salesforce

spring.security.oauth2.client.provider.salesforce.authorization-uri=https://login.salesforce.com/services/oauth2/authorize
spring.security.oauth2.client.provider.salesforce.token-uri=https://login.salesforce.com/services/oauth2/token
spring.security.oauth2.client.provider.salesforce.user-info-uri=https://login.salesforce.com/services/oauth2/userinfo
spring.security.oauth2.client.provider.salesforce.user-name-attribute=preferred_username 